# Generated by Django 3.1.3 on 2021-01-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/profile/avatar.png', upload_to='media/profile'),
        ),
    ]
