# Generated by Django 3.1.3 on 2021-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='writer',
            field=models.BooleanField(default=False),
        ),
    ]
