# Generated by Django 3.1.3 on 2021-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210117_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pic_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
