# Generated by Django 3.0.8 on 2021-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_pic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('culture', 'Culture'), ('food', 'Food'), ('health', 'Health'), ('media', 'Media'), ('opinion', 'Opinion'), ('programing', 'Programing'), ('world', 'World'), ('sport', 'Sport')], default='sport', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
